version: "3"

services:
  remote-clients:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID
        - USER_GID
        - CURRENT_WORKING_DIR
    volumes:
      - ${CURRENT_WORKING_DIR}:${CURRENT_WORKING_DIR}:cached
